### Seguem abaixo os links de documentações das libs utilizadas neste código:
#### [Python Control Systems Library (python-control) (en-US)](https://python-control.readthedocs.io/en/0.8.0/)
#### [Python Control - Módulo de compatibilidade com o MATLAB (en-US)](https://python-control.readthedocs.io/en/latest/matlab.html)
#### [NumPy (en-US)](http://www.numpy.org/)
#### [Matplotlib is a Python 2D plotting library... (en-US)](https://matplotlib.org/)


### Vídeos:
#### [PYTHON - APRENDA MAIS SOBRE NUMPY (pt-BR)](https://www.youtube.com/watch?v=9Ww-czakWrs) | Canal Youtube: Código Logo - Programação e Inteligência Artificial
#### [Gráficos com Python e Matplotlib #1: Construindo seu primeiro gráfico](https://www.youtube.com/watch?v=UZfnPkkLCA0) | Canal Youtube: PyCursos

##### Lembrete: A linha "from control.matlab import *" insere à disposição uma série de funções que buscam emular algumas das funcionalidades do MATLAB. A intenção dessas funções é prover uma simples interface às pessoas que são familiarizadas com o MATLAB.

In [1]:
import matplotlib.pyplot as plt
import control
from control.matlab import *
import numpy as np
from numpy.linalg import matrix_rank # numpy.linalg: módulo de álgebra linear do numpy

In [2]:
A = np.array([[-0.75, 0.75],[0.12,-0.15]])
B = np.array([[1.99, 0],[0, 0.33]])
C = np.eye(2,2) # Matriz identidade tamanho 2x2
D = np.zeros(4).reshape(2,2) # Matriz de zeros tamanho 2x2

In [3]:
sys = ss(A,B,C,D)

In [4]:
rank_tol = 0	# Tolerância do posto de matrizes

print('Matriz de controlabilidade das entradas:')
print(ctrb(A,B))
print('\n')

print('Número de estádos com entradas controláveis: ')
print(matrix_rank(ctrb(A,B), rank_tol))
print('\n')

print('Matriz de controlabilidade das saídas:')
print(np.dot(C, ctrb(A,B)))
print('\n')

print('Número de estádos com saídas controláveis: ')
print(matrix_rank(np.dot(C, ctrb(A,B)), rank_tol))
print('\n')

print('Matriz de observabilidade:')
print(obsv(A,C))
print('\n')

print('Número de estádos observáveis: ')
print(matrix_rank(obsv(A,C)))
print('\n')

Matriz de controlabilidade das entradas:
[[ 1.99    0.     -1.4925  0.2475]
 [ 0.      0.33    0.2388 -0.0495]]


Número de estádos com entradas controláveis: 
2


Matriz de controlabilidade das saídas:
[[ 1.99    0.     -1.4925  0.2475]
 [ 0.      0.33    0.2388 -0.0495]]


Número de estádos com saídas controláveis: 
2


Matriz de observabilidade:
[[ 1.    0.  ]
 [ 0.    1.  ]
 [-0.75  0.75]
 [ 0.12 -0.15]]


Número de estádos observáveis: 
2


